add -std=gnu17 to CPPFLAGS

diff --git a/gcl/configure b/gcl/configure
--- a/gcl/configure
+++ b/gcl/configure
@@ -7000,6 +7000,61 @@ fi
 
 
 
+add_arg_to_cppflags() {
+
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for CPPFLAG $1" >&5
+printf %s "checking for CPPFLAG $1... " >&6; }
+    CPPFLAGS_ORI=$CPPFLAGS
+    CPPFLAGS="$CPPFLAGS -Werror $1 `echo $1|sed 's,-Wno-,-W,1'`"
+    if test "$cross_compiling" = yes
+then :
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+else case e in #(
+  e) cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+main (void)
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_run "$LINENO"
+then :
+  CPPFLAGS="$CPPFLAGS_ORI $1";{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; };return 0
+else case e in #(
+  e) { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; } ;;
+esac
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext \
+  conftest.$ac_objext conftest.beam conftest.$ac_ext ;;
+esac
+fi
+
+    CPPFLAGS=$CPPFLAGS_ORI
+    return 1
+
+}
+
+assert_arg_to_cppflags() {
+    if ! add_arg_to_cppflags $1 ; then { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: cannot add $1 to CPPFLAGS" >&5
+printf "%s\n" "cannot add $1 to CPPFLAGS" >&6; }; exit 1 ; fi
+    return 0
+}
+
+add_args_to_cppflags() {
+
+    while test "$#" -ge 1 ; do
+  	add_arg_to_cppflags $1
+	shift
+    done
+}
+
 add_arg_to_cflags() {
 
     { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for CFLAG $1" >&5
@@ -7126,6 +7181,8 @@ printf "%s\n" "removing $1 from LDFLAGS" >&6; }
     return 0
 
 }
+
+add_args_to_cppflags -std=gnu17
 
 add_args_to_cflags  -fsigned-char -pipe -fcommon \
                     -fno-builtin-malloc -fno-builtin-free \
